@startuml
title Class - Repository realization
class Dummy {
  -field1 : string
  #field2 : number
  +method1() : void
  +method2(param : string) : boolean
}

interface IRepository {
  +find(id : string)
  +save(entity : Dummy)
}

class DummyRepository {
  +find(id : string) : Dummy
  +save(entity : Dummy) : void
}

DummyRepository ..|> IRepository : implements
DummyRepository ..> Dummy : returns
@enduml
